import React from 'react';
import Head from "next/head";
import Header from "../../components/Header";
import {getToken} from "next-auth/jwt";
import ManageUserTagsComponent from "../../components/userTagComponent/ManageUserTagsComponent";

export async function getServerSideProps(context) {
    const secret = 'sdfkjhsdf92w5y29whg9240p34909yh09v0324703hn09eu2019';
    const token = await getToken({
        req: context.req,
        secret: secret
    });

    if (!token){
        return {
            redirect:{
                destination:'/',
                permanent:false
            }
        }
    }else{

        const response = await fetch(`http://localhost:8080/api/v1/auth-detail/user`,{headers:{
                Authorization: "Bearer "+token.accessToken
            }});
        const data = await response.json();

        return {
            props: {
                username:token.username,
                data:data,
                authorization:token.accessToken
            }
        }
    }
}

const ManageTags = ({username,data,authorization}) => {
    return (
        <div className={"text-white"}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0" />
                <link rel="icon" href="/public/favicon.ico" />
            </Head>
            <Header user={username} />
            <main>
               <ManageUserTagsComponent data={data} authorization={authorization} />
            </main>

            <footer>
            </footer>
        </div>
    );
};

export default ManageTags;