import React from 'react';
import SearchResultComponent from "../../components/searchComponent/SearchResultComponent";
import Head from "next/head";
import Header from "../../components/Header";



const Search = () => {


    return (
        <div className={"text-white"}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main>
                <SearchResultComponent />
            </main>

            <footer>
            </footer>
        </div>
    );
};

export default Search;
