import React from 'react';
import SearchResultComponent from "../../components/searchComponent/SearchResultComponent";
import Head from "next/head";
import Header from "../../components/Header";
import {getToken} from "next-auth/jwt";

export async function getServerSideProps(context) {

    const secret = 'sdfkjhsdf92w5y29whg9240p34909yh09v0324703hn09eu2019';
    const token = await getToken({
        req: context.req,
        secret: secret
    });

    const userId = token?token.id:0;

    const pageSize = 25;
    const page = context.query.page?context.query.page:1;
    const query=context.query.q;


    const response = await fetch(`http://localhost:8080/api/v1/manga/search?userId=${userId}&page=${+page-1}&size=${pageSize}&query=${query}`);

    if (response.status !== 200){
        return {
            notFound: true,
        }
    }else{
        const mangaListSSR = await response.json();
        return {
            props: {
                mangaListSSR:mangaListSSR,
                username:token?token.username:null,
                pageSize:pageSize,
            }
        }
    }

}

const Search = ({mangaListSSR,pageSize,username}) => {


    return (
        <div className={"text-white"}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header user={username} />
            <main>
                <SearchResultComponent mangaListSSR={mangaListSSR} pageSize={pageSize} />
            </main>

            <footer>
            </footer>
        </div>
    );
};

export default Search;
