import React from 'react';
import MangaTagResultComponent from "../../components/mangaTagComponent/MangaTagResultComponent";
import Head from "next/head";
import Header from "../../components/Header";

const TagResult = () => {

    return (
        <div className={"text-white"}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0" />
                <link rel="icon" href="/public/favicon.ico" />
            </Head>
            <Header />
            <main>
                <MangaTagResultComponent />
            </main>

            <footer>
            </footer>
        </div>
    );
};

export default TagResult;
