import Head from 'next/head'
import Dashboard from "../components/Dashboard";
import Header from "../components/Header";
import {useRouter} from "next/router";
import React from "react";


export default function Home() {

    const router = useRouter();
  return (
    <div className={"text-white"}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header />
      <main>
        <Dashboard />
      </main>

      <footer>
      </footer>
    </div>
  )
}
