import React from 'react';
import Head from "next/head";
import Header from "../../components/Header";
import TagsComponent from "../../components/tagsComponent/TagsComponent";
import {useRouter} from "next/router";
import ArtistsComponent from "../../components/tagsComponent/ArtistsComponent";
import CharactersComponent from "../../components/tagsComponent/CharactersComponent";
import ParodyComponent from "../../components/tagsComponent/ParodyComponent";
import GroupComponent from "../../components/tagsComponent/GroupComponent";
import CategoryComponent from "../../components/tagsComponent/CategoryComponent";

const Tags = () => {

    const router = useRouter();

    return (
        <div className={"text-white"}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main className={"container md:mx-auto md:w-3/4 md:rounded-lg w-full sm:w-full bg-neutral-800 px-8 my-4"}>
                {router.query.sourceType==="Tag"?
                    <TagsComponent />:router.query.sourceType==="Artist"?
                        <ArtistsComponent />:router.query.sourceType==="Character"?
                            <CharactersComponent />:router.query.sourceType==="Parody"?
                                <ParodyComponent />:router.query.sourceType==="Group"?
                                    <GroupComponent />:router.query.sourceType==="Category"?
                                        <CategoryComponent />:<TagsComponent />}

            </main>
            <footer>
            </footer>
        </div>
    );
};

export default Tags;
